export const GET_STATISTIC_SUCCESS = "GET_STATISTIC_SUCCESS";
export const GET_STATISTIC_FAILED = "GET_STATISTIC_FAILED";
export const GET_SPECS_SUCCESS = "GET_SPECS_SUCCESS";
export const GET_SPECS_FAILED = "GET_SPECS_FAILED";
export const GET_DEVICES_STATS_SUCCESS = "GET_DEVICES_STATS_SUCCESS";
export const GET_DEVICES_STATS_FAILED = "GET_DEVICES_STATS_FAILED";

export const TRIGGER_STATS_SEND_SUCCESS = "TRIGGER_STATS_SEND_SUCCESS";
export const TRIGGER_STATS_SEND_FAILED = "TRIGGER_STATS_SEND_FAILED";
export const GET_STATISTIC_REPORTS_SUCCESS = "GET_STATISTIC_REPORTS_SUCCESS";
export const GET_STATISTIC_REPORTS_FAILED = "GET_STATISTIC_REPORTS_FAILED";
export const GET_STATISTIC_REPORT_SUCCESS = "GET_STATISTIC_REPORT_SUCCESS";
export const GET_STATISTIC_REPORT_FAILED = "GET_STATISTIC_REPORT_FAILED";
export const UPDATE_STATISTIC_REPORT_SUCCESS = "UPDATE_STATISTIC_REPORT_SUCCESS";
export const UPDATE_STATISTIC_REPORT_FAILED = "UPDATE_STATISTIC_REPORT_FAILED";
export const DELETE_STATISTIC_REPORT_SUCCESS = "DELETE_STATISTIC_REPORT_SUCCESS";
export const DELETE_STATISTIC_REPORT_FAILED = "DELETE_STATISTIC_REPORT_FAILED";

export const CLEAR_DELETE_STATISTIC_REPORT = "CLEAR_DELETE_STATISTIC_REPORT";
export const CLEAR_UPDATE_STATISTIC_REPORT = "CLEAR_UPDATE_STATISTIC_REPORT";
export const CLEAR_STATISTIC_REPORT_ERROR = "CLEAR_STATISTIC_REPORT_ERROR";
export const SET_STATISTIC_LOADING = "SET_STATISTIC_LOADING";
export const CLEAR_STATS_SEND_SUCCESS = "CLEAR_STATS_SEND_SUCCESS";
