export const GET_DEVICES_SUCCESS = "GET_DEVICES_SUCCESS";
export const GET_DEVICES_FAILED = "GET_DEVICES_FAILED";
export const DELETE_FROM_TUYA_SUCCESS = "DELETE_FROM_TUYA_SUCCESS";
export const DELETE_FROM_TUYA_FAILED = "DELETE_FROM_TUYA_FAILED";
export const DELETE_FROM_TUYA_CLEAR_STATE = "DELETE_FROM_TUYA_CLEAR_STATE";

