// export const API_HOST = process.env.API_HOST || "https://api.fasthome.io";
// export const API_URL = process.env.API_URL || "https://api.fasthome.io/api/v1.1";
// export const API_WATCH_URL = process.env.API_URL || "https://watch-kit.fasthome.io/api";
// export const ADMIN_URL = process.env.API_URL || "https://admin.fasthome.io";
// export const SECRET = JSON.parse(process.env.REACT_APP_SECRET) || {
//     client_secret: "h1Ualk42DmMioIAYQhxXaTqKPvRrxgwNaIicAcpi",
//     grant_type: "password",
//     client_id: 5
// }
export const API_HOST = "https://api.fasthome.io";
export const API_URL = "https://api.fasthome.io/api/v1.1";
export const API_WATCH_URL = "https://watch-kit.fasthome.io/api";
export const ADMIN_URL = "https://admin.fasthome.io";
export const SECRET = {
    client_secret: "h1Ualk42DmMioIAYQhxXaTqKPvRrxgwNaIicAcpi",
    grant_type: "password",
    client_id: 5
}

export const SECRET_REFRESH =  {
    client_secret: "h1Ualk42DmMioIAYQhxXaTqKPvRrxgwNaIicAcpi",
    client_id: 5,
    grant_type: "refresh_token"
}

export const TUYA_URL = process.env.API_HOST || "https://openapi.tuyaeu.com";

export const products = [
    {
        "name": "Smart Tooothbrush",
        "ProductID": "xpnbrxeqy0yzbitb",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "111",
        "Product Category": "toothbrush_WiFi",
        "Tag": null,
        "Create Time": "2022-05-16",
        "Modified Time": "2022-05-16",

    },
    {
        "name": "G60",
        "ProductID": "76p2te7h",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：蓝牙BLE",
        "Product Model": "G60",
        "Product Category": "True Wireless Earphones",
        "Tag": null,
        "Create Time": "2022-03-23",
        "Modified Time": "2022-03-23",

    },
    {
        "name": "WIFI Tower Fan SLS with remote control",
        "ProductID": "w0qcujupcpdcauob",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE",
        "Product Model": "SLSFAN_1",
        "Product Category": "Fan(BLE+Wi-Fi)",
        "Tag": null,
        "Create Time": "2022-02-25",
        "Modified Time": "2022-02-25",

    },
    {
        "name": "Smart EU Wall Socket SLS",
        "ProductID": "pf2ahxa7siaouzoj",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSOUT_6",
        "Product Category": "Socket(BLE+Wi-Fi)",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-10-28",
        "Modified Time": "2021-11-11",

    },
    {
        "name": "SLSCAM 7",
        "ProductID": "u02aalehmkcu7mgu",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSCAM_7",
        "Product Category": "Smart Camera",
        "Tag": "深圳市创泽视科技有限公司",
        "Create Time": "2021-10-06",
        "Modified Time": "2022-03-05",

    },
    {
        "name": "Smart EU Plug IP44, SLS",
        "ProductID": "bm3qko0gmcdlsobb",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSOUT_2",
        "Product Category": "Socket(BLE+Wi-Fi)",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-09-15",
        "Modified Time": "2021-11-11",

    },
    {
        "name": "Smart WIFI Water Leak Sensor SLS",
        "ProductID": "4qjdaqldsufeqajs",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLEAK_2",
        "Product Category": "Flood Detector (Ble+Wi-Fi)",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-09-13",
        "Modified Time": "2021-09-30",

    },
    {
        "name": "Smart WiFi Infrared Motion Sensor SLS",
        "ProductID": "grbwdlfjkviz6ec5",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSPIR_2",
        "Product Category": "PIR Motion Sensor_Wi-Fi_Ble",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-09-13",
        "Modified Time": "2021-09-30",

    },
    {
        "name": "Smart WiFi Door Sensor SLS",
        "ProductID": "9t7ojzlmam1mcnpc",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSCON_2",
        "Product Category": "Door Window Sensor_Wi-Fi_Ble",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-09-13",
        "Modified Time": "2021-10-20",

    },
    {
        "name": "Smart EU USB Plug SLS",
        "ProductID": "kz1ptzbicb5hagcc",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSOUT_5",
        "Product Category": "Power Strip(BLE+Wi-Fi)",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-09-13",
        "Modified Time": "2021-11-18",

    },
    {
        "name": "Smart EU DUO-Plug (energy monitor) SLS",
        "ProductID": "pzevkqj1bcbiryiu",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSOUT_4",
        "Product Category": "Power Strip(BLE+Wi-Fi)",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-09-13",
        "Modified Time": "2021-11-11",

    },
    {
        "name": "Smart EU Plug (with energy monitor) SLS",
        "ProductID": "dbio4qncl4mt9ahm",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSOUT_3",
        "Product Category": "Socket(BLE+Wi-Fi)",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-09-13",
        "Modified Time": "2021-11-11",

    },
    {
        "name": "SLSKET_2",
        "ProductID": "t92shrehmgnkajks",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE",
        "Product Model": "slsket_2",
        "Product Category": "Smart Kettle(BLE+Wi-Fi)",
        "Tag": "宁波西摩电器有限公司",
        "Create Time": "2021-09-08",
        "Modified Time": "2021-11-28",

    },
    {
        "name": "Умные часы SLS, SLSFIT2",
        "ProductID": "zkoin8gs",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：蓝牙BLE",
        "Product Model": "SLSFIT2",
        "Product Category": "Watch\/Wristband",
        "Tag": "深圳市健云互联科技有限公司",
        "Create Time": "2021-09-07",
        "Modified Time": "2021-09-07",

    },
    {
        "name": "SLSCAM_8",
        "ProductID": "z5fy4jfsx6jcgurh",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSCAM_8",
        "Product Category": "Smart Camera",
        "Tag": "深圳市普石科技有限公司",
        "Create Time": "2021-09-02",
        "Modified Time": "2022-05-10",

    },
    {
        "name": "2 канальный модуль выкл-ля SLS, Zigbee",
        "ProductID": "nocxdeio",
        "Status": "MP",
        "Communication Type": "Zigbee",
        "Product Model": "SLSONOFF_3",
        "Product Category": "Breaker",
        "Tag": null,
        "Create Time": "2021-09-01",
        "Modified Time": "2021-09-10",

    },
    {
        "name": "1 канальный модуль выкл-ля SLS Zigbee",
        "ProductID": "dxqfrwvn",
        "Status": "MP",
        "Communication Type": "Zigbee",
        "Product Model": "SLSONOFF_2",
        "Product Category": "Breaker",
        "Tag": null,
        "Create Time": "2021-09-01",
        "Modified Time": "2021-09-10",

    },
    {
        "name": "SLSKET_1",
        "ProductID": "ub7sgarrptdbbuqu",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE",
        "Product Model": "SLSKET_1",
        "Product Category": "Smart Kettle(BLE+Wi-Fi)",
        "Tag": "中山市安联电器有限公司",
        "Create Time": "2021-08-16",
        "Modified Time": "2021-12-17",

    },
    {
        "name": "SLSCAM 6",
        "ProductID": "b9qjconceyvivzjr",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSCAM_6",
        "Product Category": "Smart Camera",
        "Tag": "深圳市创泽视科技有限公司",
        "Create Time": "2021-08-06",
        "Modified Time": "2022-04-04",

    },
    {
        "name": "SLSCAM_5",
        "ProductID": "3q7doabymd4deuam",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSCAM_5",
        "Product Category": "Smart Camera",
        "Tag": "深圳市创泽视科技有限公司",
        "Create Time": "2021-08-06",
        "Modified Time": "2022-03-21",

    },
    {
        "name": "SLSCAM 4",
        "ProductID": "bo5j7tqnsb8gxea9",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSCAM_4",
        "Product Category": "Smart Camera",
        "Tag": "深圳市创泽视科技有限公司",
        "Create Time": "2021-08-06",
        "Modified Time": "2022-04-04",

    },
    {
        "name": "SLSCAM 1",
        "ProductID": "ego4k3tlbooha0td",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSCAM_1",
        "Product Category": "Smart Camera",
        "Tag": "深圳市创泽视科技有限公司",
        "Create Time": "2021-08-06",
        "Modified Time": "2022-04-04",

    },
    {
        "name": "SLS_VC 1",
        "ProductID": "yo1ddzuh9xyqbz1b",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "slsvc_1",
        "Product Category": "Robot Vacuum",
        "Tag": "深圳华芯信息技术股份有限公司",
        "Create Time": "2021-08-06",
        "Modified Time": "2021-11-26",

    },
    {
        "name": "2 канальный Wi-Fi модуль выключателя SLS",
        "ProductID": "ub3ckqz1jmk5bzti",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE",
        "Product Model": "SLSONOFF_5",
        "Product Category": "Breaker(BLE+Wi-Fi)",
        "Tag": "深圳市科立特照明有限公司",
        "Create Time": "2021-08-03",
        "Modified Time": "2021-09-07",

    },
    {
        "name": "1 канальный Wi-Fi модуль выключателя SLS",
        "ProductID": "ahmxyehptafzv7c2",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSONOFF_4",
        "Product Category": "Breaker(BLE+Wi-Fi)",
        "Tag": null,
        "Create Time": "2021-08-03",
        "Modified Time": "2021-09-08",

    },
    {
        "name": "WIFI термостат SLS настенный ",
        "ProductID": "qmpztlcqvr1vlieb",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSTHERM",
        "Product Category": "Thermostat",
        "Tag": "厦门海晟远电子科技有限公司",
        "Create Time": "2021-07-30",
        "Modified Time": "2021-07-30",

    },
    {
        "name": "SLSLED_5",
        "ProductID": "vafaaschs1aj651y",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_5",
        "Product Category": "Light Source",
        "Tag": "浙江美科电器有限公司",
        "Create Time": "2021-07-22",
        "Modified Time": "2021-12-27",

    },
    {
        "name": "SLSBELL 3",
        "ProductID": "uomayyqjzuuujvbp",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSBELL_3",
        "Product Category": "Smart Camera",
        "Tag": "杭州觅睿科技股份有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2022-04-04",

    },
    {
        "name": "WIFI видеозвонок аккум. SLS, SLSBELL_2",
        "ProductID": "kytfikbjqrugyusn",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSBELL_2",
        "Product Category": "Smart Camera",
        "Tag": "杭州觅睿科技股份有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2021-11-10",

    },
    {
        "name": "WIFI LED ламп. LOFT SLS свеча желт. E27",
        "ProductID": "unmgs6m2ftco0bjz",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_12",
        "Product Category": "Light Source",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2022-04-15",

    },
    {
        "name": "WIFI LED ламп. LOFT SLS кругл. желт. E27",
        "ProductID": "dm06u2g3equ0sxje",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_11",
        "Product Category": "Light Source",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2022-04-15",

    },
    {
        "name": "WIFI LED ламп. LOFT SLS свеча позр. E27 ",
        "ProductID": "y0025y7x6bccrkli",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_10",
        "Product Category": "Light Source",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2022-04-15",

    },
    {
        "name": "WIFI LED ламп. LOFT SLS кругл. прзр. E27",
        "ProductID": "l1nzgsw3mkegmjcr",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_9",
        "Product Category": "Light Source",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2022-04-15",

    },
    {
        "name": "SLSLED_4",
        "ProductID": "kbvuctq3gnhx1lhs",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_4\/7",
        "Product Category": "Light Source",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2021-12-27",

    },
    {
        "name": "WIFI LED лампочка круглая SLS E27 11W",
        "ProductID": "89sia8te3zbexnir",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_2",
        "Product Category": "Light Source",
        "Tag": "宁波摩星光电有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2022-04-15",

    },
    {
        "name": "SLSLED_8",
        "ProductID": "ehibd1iauwhoamin",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_8",
        "Product Category": "Light Source",
        "Tag": "浙江美科电器有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2021-12-27",

    },
    {
        "name": "SLSLED_3\/6",
        "ProductID": "ddxfjibr5carfetk",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_3\/6",
        "Product Category": "Light Source",
        "Tag": "浙江美科电器有限公司",
        "Create Time": "2021-07-16",
        "Modified Time": "2021-12-27",

    },
    {
        "name": "Привод управления клапаном SLS WIFI",
        "ProductID": "6ngogepndk4y0xdt",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE",
        "Product Model": "SLSVLV_1",
        "Product Category": "Socket(BLE+Wi-Fi)",
        "Tag": "杭州久诚电子有限公司",
        "Create Time": "2021-07-02",
        "Modified Time": "2021-11-24",

    },
    {
        "name": "SLSKET_1",
        "ProductID": "unpj6o5vfl1knrdv",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE",
        "Product Model": null,
        "Product Category": "Smart Kettle(BLE+Wi-Fi)",
        "Tag": "中山市安联电器有限公司",
        "Create Time": "2021-04-27",
        "Modified Time": "2021-12-17",

    },
    {
        "name": "Термостат для теплых полов Zigbee",
        "ProductID": "9dil1tvt",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "THERMZ_I2",
        "Product Category": "Thermostat",
        "Tag": "厦门海晟远电子科技有限公司",
        "Create Time": "2021-04-14",
        "Modified Time": "2021-05-20",

    },
    {
        "name": "Термостат для теплых полов WIFI",
        "ProductID": "hw235oxexazbuicd",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "THERMW_ING2",
        "Product Category": "Thermostat",
        "Tag": "厦门海晟远电子科技有限公司",
        "Create Time": "2021-04-14",
        "Modified Time": "2021-04-14",

    },
    {
        "name": "Термостат на радиатор ZIGBEE",
        "ProductID": "edaqr2fc",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "THERMZ_ING",
        "Product Category": "Thermostat",
        "Tag": "厦门海晟远电子科技有限公司",
        "Create Time": "2021-04-14",
        "Modified Time": "2021-05-20",

    },
    {
        "name": "Zigbee хаб ",
        "ProductID": "tej49jh7rlm2hefr",
        "Status": "MP",
        "Communication Type": "Wi-Fi,Zigbee",
        "Product Model": "HUBZ_ING",
        "Product Category": "Wireless Gateway(Zigbee)",
        "Tag": "深圳麦乐克传感技术有限公司",
        "Create Time": "2021-04-09",
        "Modified Time": "2021-05-21",

    },
    {
        "name": "IR пульт ДУ",
        "ProductID": "4s4vccce8bmqafzp",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi,蓝牙BLE,红外",
        "Product Model": "IR_ING2",
        "Product Category": "Universal Remote Control",
        "Tag": "杭州久诚电子有限公司",
        "Create Time": "2021-04-09",
        "Modified Time": "2021-05-20",

    },
    {
        "name": "IR пульт ДУ",
        "ProductID": "zdkszgpccmai8dum",
        "Status": "Developing",
        "Communication Type": "Wi-Fi,蓝牙BLE,红外",
        "Product Model": "IR_ING1",
        "Product Category": "Universal Remote Control",
        "Tag": "杭州久诚电子有限公司",
        "Create Time": "2021-04-09",
        "Modified Time": "2021-05-20",

    },
    {
        "name": "Привод управления клапаном ZIGBEE",
        "ProductID": "nhpdanfx",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "VALVE_ING",
        "Product Category": "Socket",
        "Tag": "杭州久诚电子有限公司",
        "Create Time": "2021-04-09",
        "Modified Time": "2021-04-09",

    },
    {
        "name": "SLSOUT_1",
        "ProductID": "ivsbsmufy0olpew0",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSOUT_1",
        "Product Category": "Socket(BLE+Wi-Fi)",
        "Tag": "绍兴美科电器进出口有限公司",
        "Create Time": "2021-04-08",
        "Modified Time": "2021-09-25",

    },
    {
        "name": "SLSVLV_1",
        "ProductID": "4gdev7nqj6nquqhf",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSVLV_1",
        "Product Category": "Socket (Wi-Fi)",
        "Tag": "杭州久诚电子有限公司",
        "Create Time": "2021-03-30",
        "Modified Time": "2021-04-02",

    },
    {
        "name": "SLSVLV_1Z",
        "ProductID": "edbsj0wg",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSVLV_1Z",
        "Product Category": "Socket",
        "Tag": "杭州久诚电子有限公司",
        "Create Time": "2021-03-30",
        "Modified Time": "2021-04-02",

    },
    {
        "name": "SLSONOFF_1",
        "ProductID": "3n75g8hqnjld56y4",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSONOFF_1",
        "Product Category": "Breaker(BLE+Wi-Fi)",
        "Tag": "绍兴美科电器进出口有限公司",
        "Create Time": "2021-03-30",
        "Modified Time": "2021-04-02",

    },
    {
        "name": "SLSLED_1",
        "ProductID": "hbgsfruiyar359vb",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_1",
        "Product Category": "Light Source",
        "Tag": "绍兴美科电器进出口有限公司",
        "Create Time": "2021-03-29",
        "Modified Time": "2021-04-02",

    },
    {
        "name": "SLSBELL_1",
        "ProductID": "er2cjzhaq2zr7qqc",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": null,
        "Product Category": "Smart Camera",
        "Tag": "杭州觅睿科技有限公司",
        "Create Time": "2020-12-14",
        "Modified Time": "2021-02-01",

    },
    {
        "name": "SLSCAM_3",
        "ProductID": "b6dmiyt5ghhbyrgl",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": null,
        "Product Category": "Smart Camera",
        "Tag": "杭州觅睿科技有限公司",
        "Create Time": "2020-12-09",
        "Modified Time": "2021-02-01",

    },
    {
        "name": "SLSCAM_2",
        "ProductID": "0l2zni9zwfd9floj",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": null,
        "Product Category": "Smart Camera",
        "Tag": "杭州觅睿科技有限公司",
        "Create Time": "2020-11-18",
        "Modified Time": "2021-01-29",

    },
    {
        "name": "SLSWAL_1",
        "ProductID": "07rothr32mukyrtm",
        "Status": "MP",
        "Communication Type": "Wi-Fi",
        "Product Model": "SLSWAL_1",
        "Product Category": "Switch (Wi-Fi)",
        "Tag": "深圳市罡狮科技有限公司",
        "Create Time": "2020-09-15",
        "Modified Time": "2020-11-24",

    },
    {
        "name": "SLSVLV_1",
        "ProductID": "4uyih6gtc3ajw8ck",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": "SLSVLV_1",
        "Product Category": "Switch (Wi-Fi)",
        "Tag": "深圳市罡狮科技有限公司",
        "Create Time": "2020-08-31",
        "Modified Time": "2020-08-31",

    },
    {
        "name": "SLSBELL_1",
        "ProductID": "55ulksdpyvoifgqi",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": null,
        "Product Category": "Smart Camera",
        "Tag": null,
        "Create Time": "2020-08-17",
        "Modified Time": "2020-08-25",

    },
    {
        "name": "SLSCAM_3",
        "ProductID": "1clgv6xkgrttziku",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": null,
        "Product Category": "Smart Camera",
        "Tag": null,
        "Create Time": "2020-08-17",
        "Modified Time": "2020-08-18",

    },
    {
        "name": "SLSCAM_2",
        "ProductID": "xa8fik8emu3fz8xa",
        "Status": "Developing",
        "Communication Type": "联网方式（Net Pairing Mode）：Wi-Fi",
        "Product Model": null,
        "Product Category": "Smart Camera",
        "Tag": null,
        "Create Time": "2020-08-17",
        "Modified Time": "2020-08-24",

    },
    {
        "name": "SLSONOFF_1",
        "ProductID": "j6emm3upsqsg5nau",
        "Status": "MP",
        "Communication Type": "Wi-Fi",
        "Product Model": "SLSONOFF_1",
        "Product Category": "Socket (Wi-Fi)",
        "Tag": null,
        "Create Time": "2020-08-12",
        "Modified Time": "2020-08-28",

    },
    {
        "name": "SLSONOFF_1",
        "ProductID": "r1ojeampy4q4ok9f",
        "Status": "MP",
        "Communication Type": "Wi-Fi",
        "Product Model": "SLSONOFF_1",
        "Product Category": "Breaker (Wi-Fi)",
        "Tag": null,
        "Create Time": "2020-07-31",
        "Modified Time": "2020-09-22",

    },
    {
        "name": "SLSLED_1",
        "ProductID": "rd8v1uhigalrwt2l",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSLED_1",
        "Product Category": "Light Source",
        "Tag": null,
        "Create Time": "2020-07-31",
        "Modified Time": "2021-03-29",

    },
    {
        "name": "SLSOUT_1",
        "ProductID": "41izsxok6w5jrgmu",
        "Status": "MP",
        "Communication Type": "Wi-Fi,蓝牙BLE",
        "Product Model": "SLSOUT_1",
        "Product Category": "Socket(BLE+Wi-Fi)",
        "Tag": null,
        "Create Time": "2020-07-31",
        "Modified Time": "2020-08-28",

    },
    {
        "name": "SLSHUB_1",
        "ProductID": "3lnuw8mqetxdrmfx",
        "Status": "MP",
        "Communication Type": "Wi-Fi,Zigbee",
        "Product Model": "SLSHUB_1",
        "Product Category": "Connector",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2020-08-28",

    },
    {
        "name": "SLSPIR_1",
        "ProductID": "5nr7ncpl",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSPIR_1",
        "Product Category": "Motion Detector",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2020-08-28",

    },
    {
        "name": "SLSLEAK_1",
        "ProductID": "hyhxm361",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSLEAK_1",
        "Product Category": "Flood Detector",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2020-08-28",

    },
    {
        "name": "SLSGAS_1",
        "ProductID": "6a1jfjy8",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSGAS_1",
        "Product Category": "Gas Detector",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2020-09-01",

    },
    {
        "name": "SLSSMO_1",
        "ProductID": "iev4cs4x",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSSMO_1",
        "Product Category": "Smoke Detector",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2020-09-01",

    },
    {
        "name": "SLSPUSH_1",
        "ProductID": "ogmpeudv",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSPUSH_1",
        "Product Category": "Wireless Switch",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2020-08-28",

    },
    {
        "name": "SLSTEMP_1",
        "ProductID": "zsfvulde",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSTEMP_1",
        "Product Category": "Temperature and Humidity Sensor",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2021-07-02",

    },
    {
        "name": "SLSCON_1",
        "ProductID": "vz0aenrq",
        "Status": "MP",
        "Communication Type": "联网方式（Net Pairing Mode）：Zigbee",
        "Product Model": "SLSCON_1",
        "Product Category": "Contact Sensor",
        "Tag": null,
        "Create Time": "2020-07-30",
        "Modified Time": "2020-08-28",

    }
]
